### ISSUE TITLE
TypeError: this._withConnection is not a function

### ISSUE THREAD

**Issue by Kaexburli** [Mohammer5/node-kraken-ws#5]
Hi,

I have installed the npm install module but I get the following error when I test the ping method 

`TypeError: this._withConnection is not a function`

the _withConnection method does not exist anywhere in the code.

**Comment by Mohammer5** [comment]
Hey, thanks for the bug report, I'll take a look later

**Comment by Mohammer5** [comment]
Fixed in [version 3.1.2](https://www.npmjs.com/package/node-kraken-ws/v/3.1.2)
