### ISSUE TITLE
Do you have an example available?

### ISSUE THREAD

**Issue by gvdhoven** [Mohammer5/node-kraken-ws#7]
Hi, i want to subscribe to the latest prices of a pair. I now have this code;

```
const KrakenWebsocket = require('node-kraken-ws');

(async () => {
  const instance = new KrakenWebsocket.KrakenWSPublic();
  await instance.connect();
  const { channelID } = await instance.subscribeToSpread({ 'pair': 'CRV/EUR' });
})();
```

But i can't seem to get the right code in order for incoming updates to arrive. Got any pointers?

**Comment by Mohammer5** [comment]
You closed the issue, did you manage to get it to work?
I haven't touched this code in a while, I guess it makes sense to add some examples to illustrate how to use the library.
if you got some working code, I could add it to the readme
